keys:
  # keys derived from ~/.ssh/id_ed25519
  - &amba age17hew4gnwapvvv53vyzmcgsk8y65spqg79r0kzs2dfpacteewts7s5dqdwz
  - &ambp age1p5tysfdy70seyxgvzlshe6hgryf9eww040qjz3revkcxf5cq0yfqs6qds0
  - &coolermaster age12rm25vwjs4uqx2lc9l3qleuz2neuz8gtv7ma5wmr78vdxcaxuddq8k6632

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *amba
          - *ambp
          - *coolermaster
