{ config, pkgs, lib, ... }:

{
  # Autostart is handled by launchd, not by AeroSpace itself (see start-at-login
  # below). AeroSpace's own start-at-login registers a macOS login item that
  # hard-codes the bundle path it was launched from -- a /nix/store path that
  # changes with every package update, so the login item silently goes stale and
  # AeroSpace stops coming up after the next reboot. The launchd agent is
  # regenerated on every switch and therefore always points at the current path.
  #
  # An earlier attempt at this agent was reverted in 4312a75 because AeroSpace
  # stayed alive but its window-management server never came up. The cause was
  # the ProgramArguments path: it went through the
  # ~/Applications/Home Manager Apps/AeroSpace.app symlink. Launch the executable
  # from the store path directly -- that is also what nix-darwin's own
  # services.aerospace module does.
  launchd.agents.aerospace = {
    enable = true;
    config = {
      ProgramArguments = [
        "${pkgs.aerospace}/Applications/AeroSpace.app/Contents/MacOS/AeroSpace"
      ];
      RunAtLoad = true;
      KeepAlive = true;
    };
  };

  xdg.configFile."aerospace/aerospace.toml".text = ''
    # Generated by Home Manager
    # Managed by the launchd agent above; AeroSpace must not register itself.
    start-at-login = false
    enable-normalization-flatten-containers = false
    enable-normalization-opposite-orientation-for-nested-containers = false
    accordion-padding = 30
    default-root-container-layout = "tiles"
    default-root-container-orientation = "auto"
    on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
    automatically-unhide-macos-hidden-apps = false

    # AeroSpace doesn't inherit the Nix profile PATH.
    # We inject the absolute Nix store paths to ensure sketchybar, aerospace, and borders can be found.
    # For borders, we run the Home Manager generated bordersrc script so it picks up our config options.
    after-startup-command = [
      "exec-and-forget /bin/bash -c 'PATH=${pkgs.aerospace}/bin:${pkgs.sketchybar}/bin:${pkgs.jankyborders}/bin:$PATH sketchybar'",
      "exec-and-forget /bin/bash -c 'PATH=${pkgs.sketchybar}/bin:${pkgs.jankyborders}/bin:$PATH ~/.config/borders/bordersrc'"
    ]

    exec-on-workspace-change = [
      "/run/current-system/sw/bin/bash",
      "-c",
      "PATH=${pkgs.aerospace}/bin:${pkgs.sketchybar}/bin:$PATH sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"
    ]

    [key-mapping]
    preset = "qwerty"

    [gaps]
    inner.horizontal = 0
    inner.vertical = 0
    outer.bottom = 0
    outer.left = 0
    outer.right = 0
    outer.top = [{ monitor."Built-in Retina Display" = 0 }, 33]

    [mode.main.binding]
    alt-enter = "exec-and-forget open -na alacritty"
    alt-shift-q = "close --quit-if-last-window"
    alt-slash = "layout tiles horizontal vertical"
    alt-comma = "layout accordion horizontal vertical"
    alt-h = "focus left"
    alt-j = "focus down"
    alt-k = "focus up"
    alt-l = "focus right"
    alt-shift-h = "move left"
    alt-shift-j = "move down"
    alt-shift-k = "move up"
    alt-shift-l = "move right"
    alt-1 = "workspace 1"
    alt-2 = "workspace 2"
    alt-3 = "workspace 3"
    alt-4 = "workspace 4"
    alt-5 = "workspace 5"
    alt-6 = "workspace 6"
    alt-7 = "workspace 7"
    alt-8 = "workspace 8"
    alt-9 = "workspace 9"
    alt-0 = "workspace 10"
    alt-minus = "workspace 11"
    alt-equal = "workspace 12"
    alt-shift-1 = "move-node-to-workspace 1"
    alt-shift-2 = "move-node-to-workspace 2"
    alt-shift-3 = "move-node-to-workspace 3"
    alt-shift-4 = "move-node-to-workspace 4"
    alt-shift-5 = "move-node-to-workspace 5"
    alt-shift-6 = "move-node-to-workspace 6"
    alt-shift-7 = "move-node-to-workspace 7"
    alt-shift-8 = "move-node-to-workspace 8"
    alt-shift-9 = "move-node-to-workspace 9"
    alt-shift-0 = "move-node-to-workspace 10"
    alt-shift-minus = "move-node-to-workspace 11"
    alt-shift-equal = "move-node-to-workspace 12"
    cmd-h = []
    cmd-alt-h = []
    alt-f = "fullscreen"
    alt-e = "layout tiles horizontal vertical"
    alt-b = "split horizontal"
    alt-v = "split vertical"
    alt-shift-space = "layout floating tiling"
    alt-tab = "workspace-back-and-forth"
    alt-shift-tab = "move-workspace-to-monitor --wrap-around next"
    ctrl-alt-h = "workspace --wrap-around prev"
    ctrl-alt-l = "workspace --wrap-around next"
    shift-alt-backspace = "workspace-back-and-forth"
    alt-shift-semicolon = "mode service"
    alt-r = "mode resize"
    alt-shift-r = "reload-config"

    [mode.resize.binding]
    h = "resize smart -50"
    left = "resize smart -50"
    l = "resize smart +50"
    right = "resize smart +50"
    esc = ["mode main"]

    [workspace-to-monitor-force-assignment]
    1 = ["SF16T", "LEN T25d-10 (1)", 1]
    2 = ["SF16T", "LEN T25d-10 (1)", 1]
    3 = ["SF16T", "PA328", "LEN T25d-10 (1)", 1]
    4 = ["BenQ PD3220U", "PA328", "LEN T25d-10 (1)", 1]
    5 = ["BenQ PD3220U", "PA328", "LEN T25d-10 (1)", 1]
    6 = ["LEN T25d-10 (2)", 2]
    7 = ["LEN T25d-10 (2)", 2]
    8 = ["LEN T25d-10 (2)", 2]
    9 = ["LEN T25d-10 (2)", 2]
    10 = ["LEN T25d-10 (2)", 2]
    11 = ["LEN T25d-10 (2)", 2]

    [mode.service.binding]
    esc = ["reload-config", "mode main"]
    r = ["flatten-workspace-tree", "mode main"]
    f = ["layout floating tiling", "mode main"]
    backspace = ["close-all-windows-but-current", "mode main"]
    alt-shift-h = ["join-with left", "mode main"]
    alt-shift-j = ["join-with down", "mode main"]
    alt-shift-k = ["join-with up", "mode main"]
    alt-shift-l = ["join-with right", "mode main"]
    down = "volume down"
    up = "volume up"
    shift-down = ["volume set 0", "mode main"]
  '';
}
